root = "."
tmp_dir = "tmp"

[build]
  cmd = "dlv"
  full_bin = "dlv debug --headless --listen=127.0.0.1:2345 --api-version=2 --accept-multiclient -- --env development"
  delay = 1000
  include_ext = ["go"]